### ISSUE TITLE
hanging `Installing wasm-bindgen...`

### ISSUE THREAD

**Issue by hxse** [open-spaced-repetition/fsrs-browser#13]
`git clone https://github.com/open-spaced-repetition/fsrs-browser`
`cd fsrs-browser`
`git submodule update --init --recursive`
`./prod.sh`
hanging Installing wasm-bindgen...
![image](https://github.com/open-spaced-repetition/fsrs-browser/assets/22582226/efd52e59-b349-4524-ab50-233a65970199)

**Comment by hxse** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-browser/assets/22582226/4319b8d2-397f-4986-8223-cd83885868d9)
I wait  5m 56s, it is done.

**Comment by AlexErrant** [comment]
Wow, a 6 minute wasm-opt for `./prod.sh` is pretty bad. In CI [it takes ~1min](https://github.com/open-spaced-repetition/fsrs-browser/actions/runs/8455658314/job/23163668078#step:7:249). On my machine it takes ~2min, and a subsequent incremental build takes ~20seconds.

There are two flags [here](https://github.com/open-spaced-repetition/fsrs-browser/blob/9808c9d4fdc49349c5f4a8ad98cc86bb35d09cbd/Cargo.toml#L39-L41) that control how much optimization is done in `release` mode. They didn't make much of a difference in build time on my machine, but you're certainly welcome to tweak them and see if they speed up your local build. Documentation [here](https://doc.rust-lang.org/cargo/reference/profiles.html#lto).

Currently, we have two "profiles"; `./dev.sh` and `./prod.sh`. Dev is good for rapid iteration on functions that are not `compute_parameters`, and Prod is what I use when iterating on `compute_parameters`. Sadly, I spend most of my time in Prod. If you find some flags that work better for your machine that don't reduce the training time too much, I'm willing to add a third profile! Currently training the example file on my machine takes 5883 ms.
