### ISSUE TITLE
Fsrs.testSerialization is not a function

### ISSUE THREAD

**Issue by hxse** [open-spaced-repetition/fsrs-browser#14]
run sandbox example, i get:
![image](https://github.com/open-spaced-repetition/fsrs-browser/assets/22582226/cacc6a75-116e-4720-be02-453604842379)

**Comment by ishiko732** [comment]
You need to compile `fsrs-browser` by running `./dev.sh`.

https://github.com/open-spaced-repetition/fsrs-browser/blob/9808c9d4fdc49349c5f4a8ad98cc86bb35d09cbd/src/lib.rs#L176-L177

**Comment by AlexErrant** [comment]
Yeah, that function tests whether or not I implemented (de)serialization between Javascript-land and Rust-land correctly. It's removed from `release` builds to reduce the binary size since it's for testing purposes only.
