### ISSUE TITLE
[BUG] The hard-coded timezone in anki_to_fsrs

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-browser#22]
https://github.com/open-spaced-repetition/fsrs-rs/blob/16bdf86c5053038dd6fc9bf939f395b889be9fe2/src/convertor_tests.rs#L178-L190

@AlexErrant, this function is used by fsrs-browser. It causes some problems for people in other timezone.

https://github.com/open-spaced-repetition/fsrs-browser/blob/58f27babb2bf6aea9de06820156a8213aa1712ff/sandbox/src/train.ts#L138

https://github.com/open-spaced-repetition/fsrs-browser/blob/58f27babb2bf6aea9de06820156a8213aa1712ff/src/lib.rs#L32-L44

**Comment by AlexErrant** [comment]
Since this is a bug in fsrs-browser, and not in fsrs-rs's test suite, please feel free to transfer this issue there!

**Comment by AlexErrant** [comment]
> Do you plan to add a timezone argument for the input? Or a timestamp like `next_day_at` of Anki? [[Ref.](https://github.com/open-spaced-repetition/fsrs-browser/pull/24#issuecomment-2080852403)]

I'm currently leaning in the direction of adding a `minute_offset` parameter (and removing `next_day_starts_at: i64, timezone: Tz`), as seen [here](https://github.com/open-spaced-repetition/fsrs-rs/compare/fsrs-browser...AlexErrant:fsrs-rs:fsrs-browser#diff-fe0a8c3a6dd28dd173ae97266de40ce47866fccf9d35a820fd66a25e8fe5556fR78). (WIP, not fully committed to this idea yet.)

If I use `chrono_tz`'s [parse](https://docs.rs/chrono-tz/latest/chrono_tz/#:~:text=You%20can%20convert%20a%20timezone%20string%20to%20a%20timezone%20using%20the%20FromStr%20trait), that means shipping the timezone database with `fsrs-browser`, which _significantly_ increases the package size. Instead, I think I'm going to rely on the browser's built-in timezone database (via `new Date().getTimezoneOffset()`) to get the `minute_offset` which I'll pass on to fsrs-rs. I'll tag you and ishiko on the PR when I'm happier with my line of thought/code.

**Comment by L-M-Sherlock** [comment]
The `minute_offset` is not very readable. Could you provide an example or document?

If the previous `next_day_starts_at` is 4 and the timezone is UTC+8:00, what's the `minute_offset` for current method?
