### ISSUE TITLE
Allow CI to open PRs?

### ISSUE THREAD

**Issue by AlexErrant** [open-spaced-repetition/fsrs-browser#29]
@L-M-Sherlock would you be willing to enable the option called "Allow GitHub Actions to create and approve pull requests" described [here](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#preventing-github-actions-from-creating-or-approving-pull-requests)? I think this link should go to the appropriate page: https://github.com/organizations/open-spaced-repetition/settings/actions

I'm trying to [get CI to open a PR](https://github.com/open-spaced-repetition/fsrs-browser/blob/1340b789969f78a89e096da83e62b852e9a4473b/.github/workflows/sync-with-fsrs-rs.yml#L145-L168) when it fails to sync with fsrs-rs (which should in turn trigger an email for me and tell me there's a problem.) However, [the repo's "Allow GitHub Actions to create and approve pull requests" option](https://github.com/open-spaced-repetition/fsrs-browser/settings/actions#:~:text=Allow%20GitHub%20Actions%20to%20create%20and%20approve%20pull%20requests) is greyed out because the org doesn't have the option enabled.

**Comment by L-M-Sherlock** [comment]
OK:

<img width="660" alt="image" src="https://github.com/user-attachments/assets/3d02ef63-da47-48a5-afc9-bf76c0c82df8">
