### ISSUE TITLE
[Question] What's the next step of this repo?

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-browser#8]
Would you like to release a npm package or something else? Or build an application based on fsrs-browser?

**Comment by AlexErrant** [comment]
> Would you like to release a npm package

Already done :) https://www.npmjs.com/package/fsrs-browser

> Or build an application based on fsrs-browser?

Working on it 🤪 https://github.com/AlexErrant/Pentive

**Comment by AlexErrant** [comment]
> What's the next step of this repo?

If/when you cut a fsrs-rs release with burn v0.12.1 I'll follow suit. I'm currently on fsrs-rs v0.2.0

**Comment by L-M-Sherlock** [comment]
Thanks for your answer!
